name: Multi-cloud Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster: [eks, aks]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set kube context
      run: |
        if [ "${{ matrix.cluster }}" == "eks" ]; then
          aws eks update-kubeconfig --name your-eks-cluster --region us-east-1
        else
          az aks get-credentials --resource-group your-rg --name your-aks-cluster
        fi

    - name: Helm Deploy auth-service
      run: helm upgrade --install auth-service ./helm-charts/auth-service --set image.repository=<your_registry>/auth-service
